server:
  port: 8080

spring:
  datasource:
    druid:
      default-auto-commit: true
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      log-abandoned: true
      max-active: 50
      max-wait: 1000
      min-evictable-idle-time-millis: 25200000
      min-idle: 1
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      url: jdbc:mysql://localhost:3306/demo?useSSL=false&characterEncoding=utf8
      username: root
      password: 123456


  redis:
    host: localhost
    port: 6379
    password: 123456

mybatis:
  type-aliases-package: com.example.demo.repository.orm
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
      - com.example.demo.repository.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

